/**
 * Audit Models
 * Models for audit events, pagination, and reporting
 * Aligned with backend audit-service DTOs
 */

// ============================================
// EVENT TYPES
// ============================================

export enum EventType {
  // User events
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_REGISTER = 'USER_REGISTER',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_PASSWORD_CHANGE = 'USER_PASSWORD_CHANGE',
  USER_PASSWORD_RESET = 'USER_PASSWORD_RESET',
  USER_MFA_ENABLED = 'USER_MFA_ENABLED',
  USER_MFA_DISABLED = 'USER_MFA_DISABLED',

  // Account events
  ACCOUNT_CREATE = 'ACCOUNT_CREATE',
  ACCOUNT_UPDATE = 'ACCOUNT_UPDATE',
  ACCOUNT_DELETE = 'ACCOUNT_DELETE',
  ACCOUNT_SUSPEND = 'ACCOUNT_SUSPEND',
  ACCOUNT_ACTIVATE = 'ACCOUNT_ACTIVATE',

  // Transaction events
  TRANSACTION_CREATE = 'TRANSACTION_CREATE',
  TRANSACTION_UPDATE = 'TRANSACTION_UPDATE',
  TRANSACTION_APPROVE = 'TRANSACTION_APPROVE',
  TRANSACTION_REJECT = 'TRANSACTION_REJECT',
  TRANSACTION_CANCEL = 'TRANSACTION_CANCEL',

  // Payment events
  PAYMENT_CREATE = 'PAYMENT_CREATE',
  PAYMENT_APPROVED = 'PAYMENT_APPROVED',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  // Security events
  SECURITY_ALERT = 'SECURITY_ALERT',
  ACCESS_DENIED = 'ACCESS_DENIED',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  FAILED_LOGIN_ATTEMPT = 'FAILED_LOGIN_ATTEMPT',
  MULTIPLE_FAILED_LOGINS = 'MULTIPLE_FAILED_LOGINS',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',

  // System events
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  API_CALL = 'API_CALL',
  DATA_EXPORT = 'DATA_EXPORT',
  DATA_IMPORT = 'DATA_IMPORT',
  CONFIGURATION_CHANGE = 'CONFIGURATION_CHANGE'
}

// ============================================
// AUDIT EVENT
// ============================================

/**
 * Main Audit Event entity
 * Represents a single auditable event in the system
 */
export interface AuditEvent {
  // Core fields
  id?: string;                    // UUID generated by backend
  eventType: string;              // Type of event (from EventType enum)
  userId?: number | null;         // User ID who triggered the event
  username?: string;              // Username (optional, for display)
  timestamp?: string;             // ISO 8601 timestamp (e.g., "2025-01-06T10:30:00Z")

  // Service information
  service?: string;               // Microservice that generated the event (e.g., "auth-service")
  serviceVersion?: string;        // Version of the service

  // Risk and security
  riskScore?: number;             // Risk score (0.0 to 1.0)
  severity?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

  // Request details
  ipAddress?: string;             // IP address of the request
  userAgent?: string;             // Browser/client user agent
  location?: string;              // Geographic location (if available)

  // Action details
  action?: string;                // Specific action performed
  resource?: string;              // Resource affected (e.g., "account:123")
  resourceType?: string;          // Type of resource (e.g., "ACCOUNT", "USER")

  // Result
  success?: boolean;              // Whether the action succeeded
  errorMessage?: string;          // Error message if failed
  errorCode?: string;             // Error code if failed

  // Additional data
  details?: any;                  // JSON object with additional details
  metadata?: Record<string, any>; // Additional metadata

  // Compliance
  complianceFlags?: string[];     // Compliance tags (e.g., ["GDPR", "PCI-DSS"])
  retentionPeriod?: number;       // Retention period in days

  // Verification
  verified?: boolean;             // Whether event integrity was verified
  hash?: string;                  // Event hash for integrity verification
}

// ============================================
// PAGINATION
// ============================================

/**
 * Generic pagination wrapper
 * Used for paginated responses from the audit service
 */
export interface AuditPage<T> {
  content: T[];                   // Array of items for current page
  totalElements: number;          // Total number of items across all pages
  totalPages: number;             // Total number of pages
  page: number;                   // Current page number (0-indexed)
  size: number;                   // Page size
  first?: boolean;                // Whether this is the first page
  last?: boolean;                 // Whether this is the last page
  numberOfElements?: number;      // Number of elements in current page
}

/**
 * Pagination request parameters
 */
export interface PageRequest {
  page?: number;                  // Page number (default: 0)
  size?: number;                  // Page size (default: 20)
  sortBy?: string;                // Field to sort by (default: "timestamp")
  sortDir?: 'ASC' | 'DESC';       // Sort direction (default: "DESC")
}

// ============================================
// SEARCH AND FILTERING
// ============================================

/**
 * Search criteria for audit events
 */
export interface AuditSearchCriteria {
  userId?: number;                // Filter by user ID
  username?: string;              // Filter by username
  eventType?: string;             // Filter by event type
  service?: string;               // Filter by service
  startDate?: string;             // Start of date range (ISO 8601)
  endDate?: string;               // End of date range (ISO 8601)
  minRiskScore?: number;          // Minimum risk score
  maxRiskScore?: number;          // Maximum risk score
  severity?: string;              // Filter by severity
  success?: boolean;              // Filter by success status
  ipAddress?: string;             // Filter by IP address
  complianceFlag?: string;        // Filter by compliance flag
  page?: number;                  // Page number
  size?: number;                  // Page size
}

// ============================================
// AUDIT REPORT
// ============================================

/**
 * Audit Report Job
 * Represents an asynchronous report generation job
 */
export interface AuditReportJob {
  jobId: string;                  // Unique job identifier
  status: AuditReportStatus;      // Current status of the job
  format?: 'PDF' | 'CSV' | 'EXCEL'; // Report format
  startDate?: string;             // Report start date
  endDate?: string;               // Report end date
  filters?: AuditSearchCriteria;  // Filters applied to the report
  downloadUrl?: string;           // URL to download the completed report
  createdAt?: string;             // When the job was created
  startedAt?: string;             // When processing started
  completedAt?: string;           // When the job completed
  expiresAt?: string;             // When the download link expires
  error?: string;                 // Error message if job failed
  progress?: number;              // Progress percentage (0-100)
  totalRecords?: number;          // Total number of records in report
}

/**
 * Audit Report Status
 */
export type AuditReportStatus =
  | 'PENDING'       // Job created but not started
  | 'IN_PROGRESS'   // Job is being processed
  | 'COMPLETED'     // Job completed successfully
  | 'FAILED'        // Job failed
  | 'CANCELLED'     // Job was cancelled
  | 'EXPIRED';      // Download link expired

/**
 * Report Generation Request
 */
export interface AuditReportRequest {
  startDate: string;              // Start date (ISO 8601)
  endDate: string;                // End date (ISO 8601)
  format?: 'PDF' | 'CSV' | 'EXCEL'; // Report format (default: PDF)
  filters?: AuditSearchCriteria;  // Additional filters
  includeDetails?: boolean;       // Include detailed event data
}

// ============================================
// STATISTICS AND ANALYTICS
// ============================================

/**
 * User Activity Summary
 */
export interface UserActivitySummary {
  userId: number;
  username: string;
  totalEvents: number;
  successfulEvents: number;
  failedEvents: number;
  averageRiskScore: number;
  lastActivity: string;
  mostCommonEventTypes: EventTypeCount[];
  suspiciousActivityCount: number;
}

/**
 * Event Type Count
 */
export interface EventTypeCount {
  eventType: string;
  count: number;
  percentage: number;
}

/**
 * System Audit Statistics
 */
export interface AuditStatistics {
  totalEvents: number;
  eventsToday: number;
  eventsThisWeek: number;
  eventsThisMonth: number;
  averageRiskScore: number;
  highRiskEvents: number;
  failedEvents: number;
  topEventTypes: EventTypeCount[];
  topUsers: UserActivitySummary[];
  eventsByService: ServiceEventCount[];
}

/**
 * Service Event Count
 */
export interface ServiceEventCount {
  service: string;
  count: number;
  percentage: number;
}

/**
 * Security Report
 */
export interface SecurityReport {
  userId: number;
  username: string;
  period: string;                 // e.g., "30 days"
  suspiciousActivities: AuditEvent[];
  failedLoginAttempts: number;
  accessDeniedCount: number;
  multipleIpLogins: boolean;
  averageRiskScore: number;
  recommendations: string[];
}

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Get display name for event type
 */
export function getEventTypeDisplayName(eventType: EventType | string): string {
  const displayNames: Record<string, string> = {
    USER_LOGIN: 'Connexion utilisateur',
    USER_LOGOUT: 'Déconnexion utilisateur',
    USER_REGISTER: 'Inscription utilisateur',
    USER_UPDATE: 'Mise à jour utilisateur',
    USER_DELETE: 'Suppression utilisateur',
    ACCOUNT_CREATE: 'Création de compte',
    ACCOUNT_UPDATE: 'Mise à jour de compte',
    TRANSACTION_CREATE: 'Création de transaction',
    PAYMENT_CREATE: 'Création de paiement',
    SECURITY_ALERT: 'Alerte de sécurité',
    SUSPICIOUS_ACTIVITY: 'Activité suspecte'
  };

  return displayNames[eventType] || eventType;
}

/**
 * Get color for risk score
 */
export function getRiskScoreColor(riskScore: number): string {
  if (riskScore >= 0.7) return '#ef4444'; // Red
  if (riskScore >= 0.4) return '#f59e0b'; // Orange
  return '#10b981'; // Green
}

/**
 * Get icon for event type
 */
export function getEventTypeIcon(eventType: EventType | string): string {
  const icons: Record<string, string> = {
    USER_LOGIN: 'login',
    USER_LOGOUT: 'logout',
    USER_REGISTER: 'person_add',
    ACCOUNT_CREATE: 'account_balance',
    TRANSACTION_CREATE: 'payment',
    SECURITY_ALERT: 'warning',
    SUSPICIOUS_ACTIVITY: 'security'
  };

  return icons[eventType] || 'event';
}
